spring.datasource.url=jdbc:postgresql://localhost:5432/telegramStorage
spring.datasource.username=managerTelegramBot
spring.datasource.password=111
telegram.bot.token=7670619887:AAE1rsNqJlgT9T5hUK8Gm98tWCguBmCzCeA

spring.liquibase.change-log=classpath:liquibase/changelog-master.yml